const shopData = {
  millkShop: {
    chtName: '迷客夏',
    menuSrc: 'https://i.imgur.com/ooNPTKl.jpg',
    bnhName: '台北新店店',
    tel: '02 2913 6058',
    fax: null,
    orderLink: 'https://bit.ly/ordermilkshop',
    linkType: 'link',
  },
  sugarcanemama: {
    chtName: '甘蔗媽媽',
    menuSrc: 'https://i.imgur.com/SPTEghW.jpg',
    bnhName: '台北古亭店',
    tel: '02 3365 3086',
    fax: null,
    orderLink: '@erv790k',
    linkType: 'line',
  },
  '50lan': {
    chtName: '50嵐',
    menuSrc: 'https://i.imgur.com/ZQATEwX.png',
    bnhName: '寶橋店',
    tel: '02 2918 8881',
    fax: null,
    orderLink: null,
    linkType: null,
  },
  teaplus: {
    chtName: '水巷茶弄',
    menuSrc: 'https://i.imgur.com/NquDsQ6.jpg',
    bnhName: '新店北新店',
    tel: '02 8911 0165',
    fax: null,
    orderLink: null,
    linkType: null,
  },
  chingshin: {
    chtName: '清心福全',
    menuSrc: 'https://i.imgur.com/6NqX0Ge.jpg',
    bnhName: '北新店',
    tel: '02 2911 3966',
    fax: null,
    orderLink: null,
    linkType: null,
  },
  blackball: {
    chtName: '黑丸嫩仙草',
    menuSrc: 'https://i.imgur.com/7mTdn2s.jpg',
    bnhName: '新店大豐店',
    tel: '02 8911 5060',
    fax: null,
    orderLink: null,
    linkType: null,
  },
  'tp-tea': {
    chtName: '茶湯會',
    menuSrc: 'https://i.imgur.com/j16UIGv.jpg',
    bnhName: '新店大坪林店',
    tel: '02 2918 8289',
    fax: null,
    orderLink: null,
    linkType: null,
  },
  jenjudan: {
    chtName: '珍煮丹',
    menuSrc: 'https://i.imgur.com/xkvt0Dl.png',
    bnhName: '新店北新店',
    tel: '02 2918 0338',
    fax: null,
    orderLink: null,
    linkType: null,
  },
  dayungs: {
    chtName: '大苑子',
    menuSrc: 'https://i.imgur.com/QCgNILK.jpg',
    bnhName: '台北木新店',
    tel: '02 2918 0338',
    fax: null,
    orderLink: null,
    linkType: null,
  },
  lephare: {
    chtName: '樂法',
    menuSrc: 'https://i.imgur.com/HaAPGnV.jpg',
    bnhName: '中興店',
    tel: '02 8914 5107',
    fax: null,
    orderLink: null,
    linkType: null,
  },
  sweetheartdessertsonly: {
    chtName: '甜在心糖水舖',
    menuSrc: 'https://i.imgur.com/ykFC8Oz.jpg',
    bnhName: '北新店',
    tel: '0921 236 196',
    fax: null,
    orderLink: null,
    linkType: null,
  },
  yifang: {
    chtName: '一芳水果茶',
    menuSrc: 'https://i.imgur.com/dC5Jsg1.jpg',
    bnhName: '新店民權店',
    tel: '02 8919 3621',
    fax: null,
    orderLink: null,
    linkType: null,
  },
  onezo: {
    chtName: '丸作食茶',
    menuSrc: 'https://i.imgur.com/Seiihpz.jpg',
    bnhName: '新店建國店',
    tel: '02 2913 0799',
    fax: null,
    orderLink: null,
    linkType: null,
  },
  comebuy: {
    chtName: 'COMEBUY',
    menuSrc: 'https://i.imgur.com/QV0ufCQ.jpg',
    bnhName: '新店北新',
    tel: '02 2911 1788',
    fax: null,
    orderLink: null,
    linkType: null,
  },
  no1_tea: {
    chtName: '台茶一號',
    menuSrc: 'https://i.imgur.com/G7E8gcT.jpg',
    bnhName: '新店七張店',
    tel: '02 8914 7372',
    fax: null,
    orderLink: null,
    linkType: null,
  },
  kqtea: {
    chtName: '康青龍',
    menuSrc: 'https://i.imgur.com/0ceO9HR.jpg',
    bnhName: '新店寶強店',
    tel: '02 2914 8066',
    fax: null,
    orderLink: null,
    linkType: null,
  },
  mubai: {
    chtName: '沐白小農',
    menuSrc: 'https://i.imgur.com/OkIz5v4.jpg',
    bnhName: '新店民權店',
    tel: '02 2912 8859',
    fax: null,
    orderLink: null,
    linkType: null,
  },
  dragon1646: {
    chtName: '吉龍糖',
    menuSrc: 'https://i.imgur.com/0jAD3de.jpg',
    bnhName: '新店建國門市',
    tel: '02 2911 1323',
    fax: null,
    orderLink: null,
    linkType: null,
  },
  cowbanana: {
    chtName: 'Cow Banana',
    menuSrc: 'https://i.imgur.com/e7ALnGY.jpg',
    bnhName: '政大店',
    tel: '02 2234 0101',
    fax: null,
    orderLink: null,
    linkType: null,
  },
  n7tealounge: {
    chtName: '柒品茶',
    menuSrc: 'https://i.imgur.com/quhherd.jpg',
    bnhName: '',
    tel: '02 2933 8181',
    fax: null,
    orderLink: null,
    linkType: null,
  },
  kebuke: {
    chtName: '可不可熟成紅茶',
    menuSrc: 'https://i.imgur.com/0N58UjV.jpg',
    bnhName: '新店民權店',
    tel: '02 2219 1313',
    fax: '02 2218 1313',
    orderLink: null,
    linkType: null,
  },
};

export default shopData;
