function importAll(r) {
  let images = {};
  r.keys().map((item, index) => { images[item.replace('./', '')] = r(item); });
  return images;
}

const images = importAll(require.context('./images/menu', false, /\.(png|jpe?g|svg)$/));

const shopData = {
  milkShop: {
    chtName: '迷客夏',
    menuSrc: images['milkshop.jpg'],
    bnhName: '台北新店店',
    tel: '02 2913 6058',
    fax: null,
    orderLink: 'https://bit.ly/ordermilkshop',
    linkType: 'link',
  },
  sugarcanemama: {
    chtName: '甘蔗媽媽',
    menuSrc: images['sugarcanemama.jpg'],
    bnhName: '台北古亭店',
    tel: '02 3365 3086',
    fax: null,
    orderLink: '@erv790k',
    linkType: 'line',
  },
  '50lan': {
    chtName: '50嵐',
    menuSrc: images['50lan.jpg'],
    bnhName: '寶橋店',
    tel: '02 2918 8881',
    fax: null,
    orderLink: null,
    linkType: null,
  },
  teaplus: {
    chtName: '水巷茶弄',
    menuSrc: images['teaplus.jpg'],
    bnhName: '新店北新店',
    tel: '02 8911 0165',
    fax: null,
    orderLink: null,
    linkType: null,
  },
  chingshin: {
    chtName: '清心福全',
    menuSrc: images['chingshin.jpg'],
    bnhName: '北新店',
    tel: '02 2911 3966',
    fax: null,
    orderLink: null,
    linkType: null,
  },
  blackball: {
    chtName: '黑丸嫩仙草',
    menuSrc: images['blackball.jpg'],
    bnhName: '新店大豐店',
    tel: '02 8911 5060',
    fax: null,
    orderLink: null,
    linkType: null,
  },
  'tp-tea': {
    chtName: '茶湯會',
    menuSrc: images['tp-tea.jpg'],
    bnhName: '新店大坪林店',
    tel: '02 2918 8289',
    fax: null,
    orderLink: null,
    linkType: null,
  },
  jenjudan: {
    chtName: '珍煮丹',
    menuSrc: images['jenjudan.png'],
    bnhName: '新店北新店',
    tel: '02 2918 0338',
    fax: null,
    orderLink: null,
    linkType: null,
  },
  dayungs: {
    chtName: '大苑子',
    menuSrc: images['dayungs.jpg'],
    bnhName: '台北木新店',
    tel: '02 2918 0338',
    fax: null,
    orderLink: null,
    linkType: null,
  },
  lephare: {
    chtName: '樂法',
    menuSrc: images['lephare.jpg'],
    bnhName: '中興店',
    tel: '02 8914 5107',
    fax: null,
    orderLink: null,
    linkType: null,
  },
  sweetheartdessertsonly: {
    chtName: '甜在心糖水舖',
    menuSrc: images['sweetheartdessertsonly.jpg'],
    bnhName: '北新店',
    tel: '0921 236 196',
    fax: null,
    orderLink: null,
    linkType: null,
  },
  yifang: {
    chtName: '一芳水果茶',
    menuSrc: images['yifang.jpg'],
    bnhName: '新店民權店',
    tel: '02 8919 3621',
    fax: null,
    orderLink: null,
    linkType: null,
  },
  onezo: {
    chtName: '丸作食茶',
    menuSrc: images['onezo.jpg'],
    bnhName: '新店建國店',
    tel: '02 2913 0799',
    fax: null,
    orderLink: null,
    linkType: null,
  },
  comebuy: {
    chtName: 'COMEBUY',
    menuSrc: images['comebuy.jpg'],
    bnhName: '新店北新',
    tel: '02 2911 1788',
    fax: null,
    orderLink: null,
    linkType: null,
  },
  no1_tea: {
    chtName: '台茶一號',
    menuSrc: images['teaplus.jpg'],
    bnhName: '新店七張店',
    tel: '02 8914 7372',
    fax: null,
    orderLink: null,
    linkType: null,
  },
  kqtea: {
    chtName: '康青龍',
    menuSrc: images['kqtea.jpg'],
    bnhName: '新店寶強店',
    tel: '02 2914 8066',
    fax: null,
    orderLink: null,
    linkType: null,
  },
  mubai: {
    chtName: '沐白小農',
    menuSrc: images['mubai.jpg'],
    bnhName: '新店民權店',
    tel: '02 2912 8859',
    fax: null,
    orderLink: null,
    linkType: null,
  },
  dragon1646: {
    chtName: '吉龍糖',
    menuSrc: images['dragon1646.jpg'],
    bnhName: '新店建國門市',
    tel: '02 2911 1323',
    fax: null,
    orderLink: null,
    linkType: null,
  },
  cowbanana: {
    chtName: 'Cow Banana',
    menuSrc: images['cowbanana.jpg'],
    bnhName: '政大店',
    tel: '02 2234 0101',
    fax: null,
    orderLink: null,
    linkType: null,
  },
  n7tealounge: {
    chtName: '柒品茶',
    menuSrc: images['n7tealounge.jpg'],
    bnhName: '',
    tel: '02 2933 8181',
    fax: null,
    orderLink: null,
    linkType: null,
  },
  kebuke: {
    chtName: '可不可熟成紅茶',
    menuSrc: images['kebuke.jpg'],
    bnhName: '新店民權店',
    tel: '02 2219 1313',
    fax: '02 2218 1313',
    orderLink: null,
    linkType: null,
  },
  chunyangtea: {
    chtName: '春陽茶事',
    menuSrc: images['chunyangtea.jpg'],
    bnhName: '新店中正店',
    tel: '02 2917 8917',
    fax: null,
    orderLink: null,
    linkType: null,
  },
  lebingo: {
    chtName: '樂冰果',
    menuSrc: images['lebingo.png'],
    bnhName: '',
    tel: '0909 030 113',
    fax: null,
    orderLink: '@lebingo',
    linkType: 'line',
  },
  louisacoffee: {
    chtName: '路易莎咖啡',
    menuSrc: images['louisacoffee.jpg'],
    bnhName: '新店寶橋店',
    tel: '02 2912 2920',
    fax: null,
    orderLink: null,
    linkType: null,
  },
  tenren: {
    chtName: '天仁茗茶',
    menuSrc: images['tenren.png'],
    bnhName: '新店寶橋店',
    tel: '02 2912 7328',
    fax: '02 2918 5590',
    orderLink: null,
    linkType: null,
  },
  dontyellatme: {
    chtName: '不要對我尖叫，日常茶間',
    menuSrc: images['dontyellatme.jpg'],
    bnhName: '新店大坪林店',
    tel: '02 2918 5255',
    fax: null,
    orderLink: null,
    linkType: null,
  },
};

export default shopData;
